const currency = {
	AUD: "Australian dollar",
	BGN: "Bulgarian lev",
	BRL: "Brazilian real",
	CAD: "Canadian dollar",
	CHF: "Swiss franc",
	CNY: "Chinese yuan renminbi",
	CZK: "Czech koruna",
	DKK: "Danish krone",
	EUR: "Euro",
	GBP: "Pound sterling",
	HKD: "Hong Kong dollar",
	HRK: "Croatian kuna",
	HUF: "Hungarian forint",
	IDR: "Indonesian rupiah",
	ILS: "Israeli shekel",
	INR: "Indian rupee",
	ISK: "Icelandic krona",
	JPY: "Japanese yen",
	KRW: "South Korean won",
	MXN: "Mexican peso",
	MYR: "Malaysian ringgit",
	NOK: "Norwegian krone",
	NZD: "New Zealand dollar",
	PHP: "Philippine peso",
	PLN: "Polish zloty",
	RON: "Romanian leu",
	RUB: "Russian rouble",
	SEK: "Swedish krona",
	SGD: "Singapore dollar",
	THB: "Thai baht",
	TRY: "Turkish lira",
	USD: "US dollar",
	ZAR: "South African rand",
};

const length = {
	m: "Meter",
	km: "Kilometers",
	cm: "Centimeter",
	mm: "Millimeter",
	um: "Micrometer",
	nm: "Nanometer",
	mi: "Mile",
	yd: "Yard",
	ft: "Foot",
	in: "Inch",
	li: "Link",
	rd: "Rod",
	ch: "Chain",
	angstrom: "Angstrom",
	mil: "Mil",
};

const area = {
	m2: "Square Meter",
	km2: "Square Kilometer",
	cm2: "Square Centimeter",
	mm2: "Square Millimeter",
	um2: "Square Micrometer",
	sqmi: "Square Mile",
	sqyd: "Square Yard",
	sqft: "Square Foot",
	sqin: "Square Inch",
	sqrd: "Square Rod",
	sqch: "Square Chain",
	sqmil: "Square Mil",
	hectare: "Hectare",
	acre: "Acre",
};

const volume = {
	m3: "Cubic Meter",
	km3: "Cubic Kilometer",
	cm3: "Cubic Centimeter",
	mm3: "Cubic Millimeter",
	l: "Litre",
	cuyd: "Cubic Yard",
	cuft: "Cubic Foot",
	cuin: "Cubic Inch",
	tablespoon: "Table Spoon",
	teaspoon: "Tea Spoon",
	min: "Minim",
	fldr: "Fluid Dram",
	floz: "Fluid Ounce",
	gi: "Gill",
	cup: "Cup",
	pt: "Pint",
	qt: "Quart",
	gal: "Gallon",
	bbl: "Beer Barrel",
	obl: "Oil Barrel",
	hogshead: "Hogshead",
	gtt: "Drop",
};

const mass = {
	kg: "Kilogram",
	g: "Gram",
	mg: "Milligram",
	tonne: "Metric Ton",
	ton: "Ton",
	gr: "Grain",
	dr: "Dram",
	oz: "Ounce",
	lbs: "Pound",
	cwt: "Hundredweight",
	stick: "Stick",
	stone: "Stone",
};

const temperature = {
	degC: "Celsius",
	degF: "Fahrenheit",
	degR: "Rankine",
	K: "Kelvin",
};

const time = {
	secs: "Second",
	msecs: "Millisecond",
	usecs: "Microsecond",
	nsecs: "Nanosecond",
	psecs: "Picosecond",
	mins: "Minute",
	hrs: "Hour",
	days: "Day",
	weeks: "Week",
	months: "Month",
	years: "Year",
	decades: "Decade",
	centuries: "Century",
	millenia: "Millenium",
};

const data = {
	b: "Bit",
	kb: "KiloBit",
	Mb: "MegaBit",
	Gb: "GigaBit",
	B: "Byte",
	kB: "KiloByte",
	MB: "MegaByte",
	GB: "GigaByte",
	TB: "TeraByte",
	PB: "PetaByte",
	EB: "ExaByte",
	ZB: "ZettaByte",
	YB: "YottaByte",
};

const titles = ["Currency", "Lenght", "Area", "Volume", "Mass", "Temperature", "Time", "Data"];
